spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            -Path=/product/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            -Path=/order/**